const mongoose = require("mongoose");
const { Schema } = mongoose;

const TestSchema = new Schema({
  personalInfo: {
    Firstname: {
      type: String,
    },
    lastname: {
      type: String,
    },
    gender: {
      type: String,
      trim: true,
    },
    dateOfBirth: Date,
    primaryMobile: String,
    secondaryMobile: String,
    email: String,
    profilepic: String,
    qualification:String,
    resume: String,
    MaritalStatus: String,
    bloodGroup: {
      type: String,
      enum: ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"],
      trim: true,
    },
    fatherName: String,
    emergencyContactNumber: String,
    emergencyContactName: String,
    presentAddress: String,
    permanentAddress: String,
    PanName: String,
    PANimageCard: String,
    Pannumber: String,
    AadharName: String,
    AadharimageCard: String,
    Aadharnumber: String,
    uan: String,
    pf: String,
    esi: String,
    nomineeName: String,
    relationshipWithNominee: String,
  },
  educationDetails: {
    schoolName: String,
    schoolLocation: String,
    yearOfPassing: String,
    overallPercentage: String,
    certificate10th: String,

    collegeName: String,
    collegeLocation: String,
    collegeYearOfPassing: String,
    collegeOverallPercentage: String,
    certificate12th: String,

    collegeName: String,
    collegeLocation: String,
    collegeYearOfPassing: String,
    collegeOverallPercentage: String,
    degreegraduate: String,
    specializationgraduate: String,
    Graduatecertificate: String,

    collegeNamePostgraduate: String,
    postgraduateLocation: String,
    yearOfPassingPostgraduate: String,
    overallPercentagePostgraduate: String,
    degreePostgraduate: String,
    specializationPostgraduate: String,
    PostGraduatecertificate: String,
  },
  Bankdetail: {
    bankAccount: String,
    bankAccountNumber: String,
    ifscCode: String,
    bankName: String,
  },

  companydetails: {
    companyName: String,
    designation: String,
    doj: String,
    dol: String,
    process: String,
    salary: String,
    SalarySlips1: String,
    SalarySlips2: String,
    SalarySlips3: String,
    RelievingLetter: String,
    ExperienceLetter: String,
    OfferLetter: String,

    companyName2: String,
    designation2: String,
    doj2: String,
    dol2: String,
    process2: String,
    salary2: String,
    OfferLetter2: String,
    ExperinaceLetter2: String,
  },
  ProffesionalRefernce: {
    refername1: String,
    referdesignation1: String,
    refercontactno1: String,
    referemailId1: String,

    refername2: String,
    referdesignation2: String,
    refercontactno2: String,
    referemailId2: String,
  },
  StatutoryandCompliance: {
    Nda: String,
    hippaAgreement: String,
    redFlag: String,
    internetSecurityUsagePolicy: String,
    internetUsagePolicy: String,
    declarationForm: String,
    nomineeForm: String,
    employeeVerification: String,
    personalDetails: String,
    userIdRequest: String,
    idCardRequest: String,
    inductionChecklist: String,
    applicationForm: String,
  },
});

const TestModel = mongoose.model("Test", TestSchema);

module.exports = { TestModel };
